### ISSUE TITLE
Merging of parallel Palo Alto pack based on pan-python

### ISSUE THREAD

**Issue by namachieli** [StackStorm-Exchange/stackstorm-paloalto#11]
## Summary 
Due to limitations with pandevice (the underlying package for the current pack) my team and I created a pack that uses pan-python (what pandevice is built on top of) for interaction with the PAN XApi, and other related APIs supported, as well as NetMiko for actions explicitly not supported by the XApi (Request and Debug commands that are reasonably safe for automation)

Our intent is to share this pack with the community because it opens up a huge range of capabilities not present in the pandevice library that we believe could help many organizations.

https://github.com/namachieli/exchange-incubator/tree/master/paloalto

## Design Summary
The design of the pack is pretty strait forward:

- YAML only action files that reference a shared set of python logic (4 API specific .py, a Netmiko .py, and a lib/base.py)
  - XAPI
  - LicAPI
  - WFAPI
  - AFAPI
  - NetMiko for raw CLI commands
- Use existing methods in pan-python where feasible
- Leverage Immutable fields and Jinja Templating to simplify a complex usage of a method (creating an object in panorama, for example)
- A Pack config structure that supports the usage of a customized list of 'connections' that can be referenced by name, in whole or partially, for connections to any Firewall devices or panoramas. (Similar to the existing pack's config logic)

A large majority of the POST/PUT actions around the XAPI involve very customized configurations (Object Names, Templates, Groups, etc). There are basically two types of actions; Native method based actions (xapi.op, xapi.set, etc) and something we coined as 'Shortcut Actions'. Shortcut actions leverage the same underlying python actions files, with immutable primary inputs, and secondary inputs prefixed with a single underscore, that are used in a Jinja template fashion for the immutable inputs, to simplify common tasks that require a well known structure with "name of your thing here" type replacements. [Example](https://github.com/namachieli/exchange-incubator/blob/master/paloalto/actions/xapi.delete.panorama.address.device_group.yaml#L63). This means that adding a "shortcut action" is as easy as providing the relevant structure, and replacement inputs. The pack logic does all the rest.

We chose to have separate actions for each API type (and Netmiko) because each one leverages shared logic in potentially slightly different ways. We felt keeping them separate at this layer simplified future changes to existing API endpoints, methods, or in the event of an addition/removal by Palo Alto of an API/Method.

## Approach for moving forward
A while back I requested some feedback in the #community channel on stackstorm_community in slack, and presented a few options of how to move forward:

1. Leave the existing pack as is, and maintain the new pack in parallel for a time, and later deprecate the old one
2. Do a hard 'replace' of the current pack with the new one, tag as a larger version change, Big warnings about no backwards compatibility.
3. Merge the logic of the packs into one pack with parallel actions (some overlaps), maintain both for a while, add warnings to older actions of future removal, etc
- Possibly others?

The loose consensus was split between 'hard replace' and 'graceful merge'.

I would love to hear thoughts an opinions on this. I assume this is a 'how' question, not an 'if' question.

My team and I are willing to do the work to get us to the end state, and would only request oversight, peer review, and minor assistance as needed.

**Comment by namachieli** [comment]
Ideally I think we would go with option 3. I would like to add some logic to existing code so that those actions spit out a loud warning that it is deprecated and will be removed in a future release.

I need to review all the existing actions an ensure that there is comparable functionality.

I think a 'migration guide' would be warranted as well that would describe what people need to do migrate over to new actions.

**Comment by nmaludy** [comment]
@namachieli yes, i think #3 a side-by-side and migration path is the best option, then we can phase the new one in and phase the old one out.

happy to do reviews of the code and excited to see this pack get some attention!

**Comment by namachieli** [comment]
Excellent then i will start working in that direction as PR for the current repo. Should we handle further collaboration in the PR?

Thanks!

**Comment by nmaludy** [comment]
Yes please!

**Comment by punkrokk** [comment]
Awesome. I have a strategy to create dynamic block lists using the data store for expiry.

**Comment by namachieli** [comment]
PR opened. Closing Issue.
