### ISSUE TITLE
Extend and cleanup pack

### ISSUE THREAD

**Issue by lampwins** [StackStorm-Exchange/stackstorm-paloalto#2]
I think this is great! I would like to extend this pack a bit in a couple of ways. I would like to support registering multiple IPs/Tags at once using bulk operations. I would like to use the [pandevice](https://github.com/PaloAltoNetworks/pandevice) library to make the actions a little easier to build out and maintain as apposed to dealing with xapi directly. I would like to restructure the pack config for firewall authentication based on the vSphere pack config model. Finally I noticed the rules in this pack have some hard coded addresses that we should take a look at. 

Do you have any thoughts on this @irom77 and @LindsayHill

**Comment by LindsayHill** [comment]
@lampwins Knock yourself out - quite happy to accept PRs here.

**Comment by irom77** [comment]
Fantastic ! I think it would be good idea to consider using the same action names as ones used in recently added pack for fortinet firewall where it makes sense. These rules were only meant to be an example, but feel free to modify them.

**Comment by lampwins** [comment]
Closed in #3
